### ISSUE TITLE
Retaper les cours, corrigé les quelques dernierès erreurs pour impression

### ISSUE THREAD

**Issue by superLinab** [superLinab/coursGalien#3]
Voici les cours qu'ils restent à vérifier : 

- [x] ./Chapitre 1 : Fonctions/#1 - Definitions, premieres proprietes, exemples/source/exercicesFonction.md
- [x] ./Chapitre 1 : Fonctions/#1 - Definitions, premieres proprietes, exemples/source/coursFonctions.md
- [ ] ./Chapitre 1 : Fonctions/#3 - Exponentielle et logarithme/source/coursFonctions3.md
- [x] ./Chapitre 1 : Fonctions/#3 - Exponentielle et logarithme/source/exerciceFonctions3.md
- [x] ./Chapitre 1 : Fonctions/#2 - Limites, continuité, dérivée/source/exerciceFonctions2.md
- [x] ./Chapitre 1 : Fonctions/#2 - Limites, continuité, dérivée/source/coursFonctions2.md
- [x] ./Points Méthodes/source/listePointMethode.md
- [ ] ./Points Méthodes/source/listeNotions.md
- [x] ./Points Méthodes/source/typeDeSuitesAuBac.md
- [ ] ./Points Méthodes/source/raisonnementparrecurrence.md
- [ ] ./Chapitre 3 : Les nombres complexes/source/coursComplexe.md
- [ ] ./Chapitre 2: Suites /source/exerciceSuite.md
- [x] ./Chapitre 2: Suites /source/newton.md
- [x] ./Chapitre 2: Suites /source/coursSuite.md

**Comment by superLinab** [comment]
Il faut revoir la taille des images des fichiers suivants : 

- [ ] /Chapitre 1 : Fonctions/#3 - Exponentielle et logarithme/source/coursFonctions3.md
- [ ] ./Chapitre 1 : Fonctions/#2 - Limites, continuité, dérivée/source/coursFonctions2.md (l'image de la tangente est bien trop grosse !
